name: Build Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu çek
        uses: actions/checkout@v3

      - name: Docker versiyonunu göster
        run: docker --version

      - name: Docker image build et
        run: docker build -t node-docker-demo .
