name: Production Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker versiyon
        run: docker --version

      - name: Docker Hub login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Docker image build et
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/node-demo:latest .

      - name: Docker image push et
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/node-demo:latest

      - name: Production deploy simülasyonu
        run: echo "Kod Production ortamına deploy edildi!"
